{% set version = "0.9.4" %}

package:
  name: panel
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/panel/panel-{{ version }}.tar.gz
  sha256: dcd5b7f078c8b4778aab58dfe3c6d9880dd7ff2d0c19bfef52db941be1dd0534
  patches:
    # Patch issue with npm package version
    - package-json-fix.patch

build:
  number: 0
  noarch: python
  entry_points:
    - panel = panel.cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
    # These are also needed at build time.
    - pyct
    - bokeh >=2.0
    - nodejs >=10.13.0
  run:
    - python >=3
    - bokeh >=2.0
    - markdown
    - param >=1.9.3
    - pyct >=0.4.4
    - pyviz_comms >=0.7.4
    - tqdm

test:
  imports:
    - panel
    - panel.io
  commands:
    - pip check
    - panel --help
  requires:
    - pip

about:
  home: https://panel.holoviz.org
  summary: A high-level app and dashboarding solution for Python
  description: |
    Panel provides tools for easily composing widgets, plots, tables, and other
    viewable objects and controls into control panels, apps, and dashboards.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - philippjfr
    - ocefpaf
